Adding check for failed venv activation

diff --git a/src/rx_selection_scripts/submit_selection b/src/rx_selection_scripts/submit_selection
--- a/src/rx_selection_scripts/submit_selection
+++ b/src/rx_selection_scripts/submit_selection
@@ -18,7 +18,11 @@ display_help()
 setup()
 {
     source $HOME/.bashrc
-    mma root_6p32
+    mma run3 
+    if [[ $? -ne 0 ]];then
+        echo "Could not set virtual environment"
+        exit 1
+    fi
 }
 # ----------------------------
 get_opts()
