Adding check for not been able to run bashrc

diff --git a/src/rx_selection_scripts/submit_selection b/src/rx_selection_scripts/submit_selection
--- a/src/rx_selection_scripts/submit_selection
+++ b/src/rx_selection_scripts/submit_selection
@@ -18,6 +18,11 @@ display_help()
 setup()
 {
     source $HOME/.bashrc
+    if [[ $? -ne 0 ]];then
+        echo "Could not run rc file"
+        exit 1
+    fi
+
     mma run3 
     if [[ $? -ne 0 ]];then
         echo "Could not set virtual environment"
