Updating for safer and easier to use shell creator
- Use set -euxo pipefail
- Add comments
- Export paths to local directories with packages
- Install from local directories with up to date code

diff --git a/src/ap_utilities_scripts/dirac_shell b/src/ap_utilities_scripts/dirac_shell
--- a/src/ap_utilities_scripts/dirac_shell
+++ b/src/ap_utilities_scripts/dirac_shell
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+set -euxo pipefail
+
 LOCAL_PATH=/tmp/${USER}/ap_utilities/env
 # ------------------------------------------------------------------
 display_help()
@@ -29,22 +31,56 @@ get_opts()
     done
 }
 # ------------------------------------------------------------------
+# Make paths to directories with python projets
+# available globally
+# 
+# Globals:
+#   APUT_PATH
+#   DMU_PATH
+# ------------------------------------------------------------------
+export_paths()
+{
+    if [[ ! -d $SFTDIR ]];then
+        echo "Software directory not found"
+        exit 1
+    fi
+
+    APUT_PATH=$SFTDIR"/ap_utilities"
+    if [[ ! -d $APUT_PATH ]];then
+        echo "ap_utilities directory not found"
+        exit 1
+    else
+        export APUT_PATH
+    fi
+
+    DMU_PATH=$SFTDIR"/dmu"
+    if [[ ! -d $DMU_PATH ]];then
+        echo "dmu directory not found"
+        exit 1
+    else
+        export DMU_PATH
+    fi
+}
+# ------------------------------------------------------------------
 make_rcfile()
 {
     export RCFILE=/tmp/bash_dirac
     export LIBPATH=$LOCAL_PATH/lib/python3.11/site-packages
 
-    echo "#!/usr/bin/env bash"                  > $RCFILE
-    echo ""                                    >> $RCFILE
-    echo "export PS1='\u@\h\$ '"               >> $RCFILE
-    echo "export PATH+=:$LOCAL_PATH/bin"       >> $RCFILE
-    echo "export PYTHONPATH+=:$LIBPATH"        >> $RCFILE
-    echo ""                                    >> $RCFILE
-    echo "echo \"-----------------------\""    >> $RCFILE
-    echo "echo \"Installing ap_utilities\""    >> $RCFILE
-    echo "echo \"-----------------------\""    >> $RCFILE
-    echo ""                                    >> $RCFILE
-    echo "pip install --prefix $LOCAL_PATH . " >> $RCFILE
+    export_paths
+
+    echo "#!/usr/bin/env bash"                           > $RCFILE
+    echo ""                                             >> $RCFILE
+    echo "export PS1='\u@\h\$ '"                        >> $RCFILE
+    echo "export PATH+=:$LOCAL_PATH/bin"                >> $RCFILE
+    echo "export PYTHONPATH+=:$LIBPATH"                 >> $RCFILE
+    echo ""                                             >> $RCFILE
+    echo "echo \"-----------------------\""             >> $RCFILE
+    echo "echo \"Installing projects    \""             >> $RCFILE
+    echo "echo \"-----------------------\""             >> $RCFILE
+    echo ""                                             >> $RCFILE
+    echo "pip install --prefix $LOCAL_PATH $APUT_PATH " >> $RCFILE
+    echo "pip install --prefix $LOCAL_PATH  $DMU_PATH " >> $RCFILE
     echo ""
     echo "Using rc file:"
     cat $RCFILE
@@ -61,12 +97,9 @@ initialize()
 # ------------------------------------------------------------------
 create_shell()
 {
-    which lb-dirac > /dev/null 2>&1
-
-    if [[ $? -ne 0 ]];then
-        echo "Cannot find lb-dirac, LHCb software not set, setting it"
-        lhcb_env
-    fi
+    set +u
+    lhcb_env
+    set -u
 
     if [[ ! -f $RCFILE ]];then
         echo "Cannot find $RCFILE"
