Add check for rapidsim status

diff --git a/src/rx_efficiencies_scripts/create_rapidsim_ntuples b/src/rx_efficiencies_scripts/create_rapidsim_ntuples
--- a/src/rx_efficiencies_scripts/create_rapidsim_ntuples
+++ b/src/rx_efficiencies_scripts/create_rapidsim_ntuples
@@ -114,6 +114,11 @@ create_ntuple()
     cd $DECAYDIR
     if [[ "$DRY_RUN" == "0" ]];then
         rapidsim $RAPIDSIM_CONFIG/$DECAY $NEVENTS 1 > $DECAY".log" 2>&1
+
+        if [[ $? -ne 0 ]];then
+            echo "Cannot generate events, see $PWD/$DECAY".log""
+            exit 1
+        fi
     fi
     cd - > /dev/null
 
