Add check for missing rapidsim

diff --git a/src/rx_efficiencies_scripts/create_rapidsim_ntuples b/src/rx_efficiencies_scripts/create_rapidsim_ntuples
--- a/src/rx_efficiencies_scripts/create_rapidsim_ntuples
+++ b/src/rx_efficiencies_scripts/create_rapidsim_ntuples
@@ -65,6 +65,14 @@ initialize()
         echo "ANADIR variable not set"
         exit 1
     fi
+
+    which rapidsim > /dev/null 2>&1
+
+    if [ $? -ne 0 ];then
+        echo ""
+        echo "Rapidsim not found"
+        exit 1
+    fi
 }
 # -----------------------
 find_decays()
